### ISSUE TITLE
Do we have to add all the standard includes specifically with the –include-dir option

### ISSUE THREAD

**Issue by Tagar** [elijahr/python-autopxd2#17]
```

$ autopxd VCEUtilities.h VCEUtilities.pxd

<stdin>:24:19: error: no include path in which to search for fstream
<stdin>:25:19: error: no include path in which to search for iomanip
<stdin>:26:20: error: no include path in which to search for iostream
<stdin>:27:20: error: no include path in which to search for stdlib.h
<stdin>:28:18: error: no include path in which to search for string
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3/bin/autopxd", line 11, in <module>
    sys.exit(cli())
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/autopxd/__init__.py", line 94, in cli
    outfile.write(translate(infile.read(), infile.name, extra_cpp_args))
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/autopxd/__init__.py", line 73, in translate
    p.visit(parse(code, extra_cpp_args=extra_cpp_args, whitelist=whitelist))
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/autopxd/__init__.py", line 48, in parse
    preprocessed = preprocess(code, extra_cpp_args=extra_cpp_args)
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/autopxd/__init__.py", line 43, in preprocess
    raise Exception('Invoking C preprocessor failed')
Exception: Invoking C preprocessor failed
```

Do we have to add all the standard includes specifically with the –include-dir option?

**Comment by elijahr** [comment]
As of v3.1.1 the new default libclang backend automatically adds system includes.
